### ISSUE TITLE
Obtaining constructed maps

### ISSUE THREAD

**Issue by YouriRombouts** [AriSaadon/RoadMapConstructionEvaluation#1]
Hello Ari, 

I am conducting research for my thesis project supervised by Frank Staals. I would like to get in contact with you to regarding constructed maps you used during your research. If you still have the constructed maps you used during your research I would very much like to receive those to use in my research.
I hope to hear from you soon.

Best regards,
Youri Rombouts

**Comment by AriSaadon** [comment]
Hey youri,Ik ben op het moment op vakantie, ik ben komende maandag terug. Ik help je zeker graag met de road map construction mappen als ik terug ben. Als je wil kunnen we een momentje afspreken. Groet,AriOn Mar 16, 2022 15:01, YouriRombouts ***@***.***> wrote:
Hello Ari,
I am conducting research for my thesis project supervised by Frank Staals. I would like to get in contact with you to regarding constructed maps you used during your research. If you still have the constructed maps you used during your research I would very much like to receive those to use in my research.
I hope to hear from you soon.
Best regards,
Youri Rombouts

**Comment by YouriRombouts** [comment]
Hi Ari,

Bedankt dat je even tijd wilt maken. Ik heb de hele maandag geen plannen
dus als je dan kan stel maar een tijdstip voor. Als maandag minder handig
is is dinsdag voor 12:00 of na 16:00 ook goed. Mijn teams email is
***@***.***

Met vriendelijke groet,
Youri Rombouts

**Comment by AriSaadon** [comment]
Zou dinsdag om 18 uur lukken voor je?AriOn Mar 17, 2022 15:59, YouriRombouts ***@***.***> wrote:

Hi Ari,



Bedankt dat je even tijd wilt maken. Ik heb de hele maandag geen plannen

dus als je dan kan stel maar een tijdstip voor. Als maandag minder handig

is is dinsdag voor 12:00 of na 16:00 ook goed. Mijn teams email is

***@***.***



Met vriendelijke groet,

Youri Rombouts

**Comment by YouriRombouts** [comment]
Ja 18:00 is goed

**Comment by AriSaadon** [comment]
Goeiemorgen youri,Ik ben gister aangekomen en toch nog wel heel moe, was een beetje hubris van me om vandaag al om 18 uur af te spreken. Zou in plaats van vandaag, morgen om 18 uur ook nog kunnen?Groet,AriOn Mar 18, 2022 11:29, YouriRombouts ***@***.***> wrote:
Ja 18:00 is goed

**Comment by YouriRombouts** [comment]
Ja we hadden dinsdag 18:00 gezegd. Maar als je wilt verplaatsen komt mij een tijdstip wat niet rond etenstijd valt ook beter uit. Zoals ik eerder al zei, ik heb buiten dinsdag middag geen andere afspraken deze week.

**Comment by AriSaadon** [comment]
Ooh het was al dinsdag, excuus dacht dat we vandaag hadden afgesproken. Dom van me. Dinsdag komt me toch wel het best uit. Qua tijdstip maakt me niet zo uit als 18 je niet goed uitkomt. Zolang het na 17 is, vind ik het best. Dus 19 of 20 ook goed. Zegmaar.Ik heb trouwens geen teams thuis.Ik ben wel bereikbaar op 0638504057Of ik kan je mijn discord sturen zodra ik thuis ben van werk.Groet,AriOn Mar 21, 2022 09:49, YouriRombouts ***@***.***> wrote:
Ja we hadden dinsdag 18:00 gezegd. Maar als je wilt verplaatsen komt mij een tijdstip wat niet rond etenstijd valt ook beter uit. Zoals ik eerder al zei, ik heb buiten dinsdag middag geen andere afspraken deze week.

**Comment by YouriRombouts** [comment]
Ja 17:00 zou beter zijn. Mijn discord is YourionY#6605

**Comment by AriSaadon** [comment]
Oei ik lees je bericht net pas, ik ben nu richting huis. Als je het goed vind, bel ik je op discord over paar minuutjes.Groet,AriOn Mar 22, 2022 13:48, YouriRombouts ***@***.***> wrote:
Ja 17:00 zou beter zijn. Mijn discord is YourionY#6605

**Comment by YouriRombouts** [comment]
Kan 19:00 ook nog? Ik ben net even naar buiten.

**Comment by AriSaadon** [comment]
19 uur lukt me juist net niet. Ik kan nu of later in de avond. Na 20 of 21 als je dat niet erg vind.AriOn Mar 22, 2022 17:27, YouriRombouts ***@***.***> wrote:

Kan 19:00 ook nog? Ik ben net even naar buiten.

**Comment by YouriRombouts** [comment]
Ik kan nu, is het dan nog nuttig?

**Comment by AriSaadon** [comment]
Hi youri,Ik had aangenomen dat het niet door zou gaan omdat ik nog niets van je had gehoord na 18. Tenzij je nu nog wilt praten, stel ik voor dat we morgen even bellen in de ochtend. Geef maar een tijdstip, ik ben de hele ochtend beschikbaar als je kan.Groet,AriOn Mar 22, 2022 18:11, YouriRombouts ***@***.***> wrote:

Ik kan nu, is het dan nog nuttig?

**Comment by AriSaadon** [comment]
Provided the requested maps in private

**Comment by YouriRombouts** [comment]
Discord lijkt me handig dan.
